project-name = "elasticBeanStack"
aws_region = "us-east-1"
 
codebucket = "elasticbeanstack"
file-name = "springdemo-0.0.1-SNAPSHOT.war"
file-path = "ansible_templates/files"
app-name = "mywebapp"
webapp-src-location = "/home/vagrant/springdemo/target"
stack-name = "64bit Amazon Linux 2 v3.4.1 running Corretto 17"
instance-profile = "myinstanceprofile"

dockerapp-name = "dockerapp"
dockerfile-name = "docker.zip"
dockerstack-name = "64bit Amazon Linux 2016.09 v2.5.2 running Docker 1.12.6"
dockerwebapp-src-location = "ansible_templates/files"
dockerfile-name = "Dockerrun.json"