---
- hosts: "{{ passed_in_hosts }}"
  tasks:
    - name: Execute install 
      ansible.builtin.shell: aws deploy push --application-name "{{ app_name }}" --s3-location s3://"{{bucket}}"/"{{zip_file}}".zip
      args:
        chdir: "{{ webapp_src_location }}"      
       