---
- hosts: "{{ passed_in_hosts }}"
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: install java
      yum:
        name: "{{ package }} "
        state: installed
      vars:
        package:
        - java-1.8.0

    - name: Copy war file
      ansible.builtin.copy:
      src: {{ war_file }}
      dest: /home/ec2-user

    - name: Run springboot application 
      ansible.builtin.shell: java -jar {{ war_file }} 