---
- hosts: "{{ passed_in_hosts }}"
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: install docker
      yum:
        name: "{{ package }} "
        state: installed
      vars:
        package:
        - docker

    - name: provide permission to ec2-user to run docker  
      ansible.builtin.shell: usermod -a -G docker ec2-user
    
    - name: start docker daemon   
      ansible.builtin.shell: systemctl start docker.service

    - name: Copy war file
      ansible.builtin.copy:
        src: "{{ war_file }}"
        dest: /home/ec2-user

    - name: Copy Docker file
      ansible.builtin.copy:
        src: "{{ docker_file }}"
        dest: /home/ec2-user

    - name: start docker daemon   
      ansible.builtin.shell: systemctl start docker.service

    - name: run docker build    
      ansible.builtin.shell: docker build -t springdemo:latest . 
    
    - name: Run springboot application 
      ansible.builtin.shell: docker run -p 8080:8080 -d springdemo:latest 