version: 0.1                                                       
                                                                   
phases:                                                            
  pre_build:                                                       
    commands:                                                      
      - echo Pre-Build started on `date`                           
  build:                                                           
    commands:                                                      
      - echo Build completed on `date`                             
      - mvn clean package                                          
      - cp target/awspipelinedemo-1.0.0-SNAPSHOT.jar codedeploy    
      - ls -lrt codedeploy                                         
                                                                   
artifacts:                                                         
  base-directory: codedeploy                                       
  files:                                                           
    - '**/*'                                                       