---
- hosts: "{{ passed_in_hosts }}"
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: install java
      yum:
        name: "{{ package }} "
        state: installed
      vars:
        package:
        - java-1.8.0-openjdk
  
    - name: copy war file
      copy: 
        src=mywebapp-0.0.1-SNAPSHOT   
        dest=/home/ec2-user
