FROM openjdk:8-jdk-alpine
MAINTAINER mahesh

EXPOSE 8080

COPY ./SpringDataTest-0.0.1-SNAPSHOT.jar SpringDataTest-0.0.1-SNAPSHOT.jar 

ENTRYPOINT ["java", "-jar", "/SpringDataTest-0.0.1-SNAPSHOT.jar"]