---
- hosts: "{{ passed_in_hosts }}"
  tasks:
    - name: Execute install 
      ansible.builtin.shell: aws s3 cp {{ file_name }} s3://"{{bucket}}"/"{{file_name}}"
      args:
        chdir: "{{ webapp_src_location }}"      
       